version: '2'
services:
    db:
      image: postgres
      volumes:
        - ./postgres:/var/lib/postgresql/data
    web:
      build: .
      command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
      volumes:
        - .:/myapp
      ports:
        - "${PORT}:${PORT}"
      depends_on:
        - db
